version: '3.8'

services:
  app:
    build: .
    container_name: courses-app
    ports:
      - "42125:42125"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=usersdb42
      - DB_USER=postgres
      - DB_PASSWORD=111LZo0l4S7dzO0PXA3KOkasw2rcMtO46hY2FbUPxS
    depends_on:
      - postgres
    volumes:
      - ./static:/app/static
    networks:
      - courses-network
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: courses-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111LZo0l4S7dzO0PXA3KOkasw2rcMtO46hY2FbUPxS
      - POSTGRES_DB=usersdb42
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - courses-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: courses-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - courses-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: courses-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - courses-network
    restart: unless-stopped

networks:
  courses-network:
    driver: bridge

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
