{
 "title": "Flask Application Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_sum / flask_http_request_duration_seconds_count"
    }
   ]
  },
  {
   "title": "HTTP Exceptions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flask_http_request_exceptions_total"
    }
   ]
  },
  {
   "title": "Total HTTP Requests by Endpoint",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "flask_http_request_total" }
   ]
  }
 ]
}